package handlers

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jung-kurt/gofpdf"
	"github.com/shakil5281/peoplehub-api/internal/models"
	"github.com/xuri/excelize/v2"
)

type jobCardLabels struct {
	JobCardTitle string
	PeriodLabel  string
	EmployeeInfo string
	Name         string
	EmployeeID   string
	Designation  string
	Department   string
	Phone        string
	JoiningDate  string
	Shift        string
	Sl           string
	Date         string
	Day          string
	InTime       string
	OutTime      string
	Hours        string
	OT           string
	LateMinutes  string
	Status       string
	Summary      string
	TotalDays    string
	Present      string
	Late         string
	Absent       string
	HalfDay      string
	Leave        string
	Weekend      string
	Holiday      string
	TotalLateMin string
	GeneratedBy  string
	PrintDate    string
}

var jobCardEnLabels = jobCardLabels{
	JobCardTitle: "JOB CARD",
	PeriodLabel:  "Period",
	EmployeeInfo: "EMPLOYEE INFORMATION",
	Name:         "Name",
	EmployeeID:   "Employee ID",
	Designation:  "Designation",
	Department:   "Department",
	Phone:        "Phone",
	JoiningDate:  "Joining Date",
	Shift:        "Shift",
	Sl:           "#",
	Date:         "Date",
	Day:          "Day",
	InTime:       "In Time",
	OutTime:      "Out Time",
	Hours:        "Hours",
	OT:           "OT",
	LateMinutes:  "Late (min)",
	Status:       "Status",
	Summary:      "Summary",
	TotalDays:    "Total Days",
	Present:      "Present",
	Late:         "Late",
	Absent:       "Absent",
	HalfDay:      "Half Day",
	Leave:        "Leave",
	Weekend:      "Weekend",
	Holiday:      "Holiday",
	TotalLateMin: "Late Minutes",
	GeneratedBy:  "Generated by PeopleHub HR & Payroll System",
	PrintDate:    "Print Date",
}

var jobCardBnLabels = jobCardLabels{
	JobCardTitle: "জব কার্ড",
	PeriodLabel:  "সময়কাল",
	EmployeeInfo: "কর্মচারীর তথ্য",
	Name:         "নাম",
	EmployeeID:   "কর্মচারী আইডি",
	Designation:  "পদবি",
	Department:   "বিভাগ",
	Phone:        "ফোন",
	JoiningDate:  "যোগদানের তারিখ",
	Shift:        "শিফট",
	Sl:           "ক্রম",
	Date:         "তারিখ",
	Day:          "বার",
	InTime:       "প্রবেশ",
	OutTime:      "প্রস্থান",
	Hours:        "ঘণ্টা",
	OT:           "ওটি",
	LateMinutes:  "বিলম্ব (মি.)",
	Status:       "অবস্থা",
	Summary:      "সারসংক্ষেপ",
	TotalDays:    "মোট দিন",
	Present:      "উপস্থিত",
	Late:         "বিলম্বে",
	Absent:       "অনুপস্থিত",
	HalfDay:      "অর্ধদিবস",
	Leave:        "ছুটি",
	Weekend:      "সাপ্তাহিক ছুটি",
	Holiday:      "উৎসব ছুটি",
	TotalLateMin: "মোট বিলম্ব",
	GeneratedBy:  "পিপলহাব এইচআর অ্যান্ড পেঅরোল সিস্টেম দ্বারা তৈরি",
	PrintDate:    "প্রিন্টের তারিখ",
}

type jobCardSection struct {
	Employee models.Employee
	Rows     []models.Attendance
}

type jobCardStats struct {
	Total, Present, Late, Absent, HalfDay, Leave, Weekend, Holiday, LateMinutes int
}

func groupJobCard(atts []models.Attendance) []jobCardSection {
	var sections []jobCardSection
	for _, a := range atts {
		if len(sections) == 0 || sections[len(sections)-1].Employee.EmployeeID != a.EmployeeID {
			sections = append(sections, jobCardSection{Employee: a.Employee})
		}
		last := &sections[len(sections)-1]
		last.Rows = append(last.Rows, a)
	}
	return sections
}

func jobCardStatsFor(rows []models.Attendance) jobCardStats {
	var st jobCardStats
	st.Total = len(rows)
	for _, a := range rows {
		switch a.Status {
		case "present":
			st.Present++
		case "late":
			st.Late++
		case "absent":
			st.Absent++
		case "half_day":
			st.HalfDay++
		case "on_leave", "leave":
			st.Leave++
		case "weekend":
			st.Weekend++
		case "holiday":
			st.Holiday++
		}
		st.LateMinutes += a.LateMinutes
	}
	return st
}

func jobCardStatusCode(s string) string {
	switch s {
	case "present":
		return "P"
	case "late":
		return "L"
	case "absent":
		return "A"
	case "half_day":
		return "HD"
	case "on_leave", "leave":
		return "V"
	case "weekend":
		return "W"
	case "holiday":
		return "H"
	}
	if s == "" {
		return "-"
	}
	return strings.ToUpper(s[:1])
}

func jobCardDateDisplay(dateStr string) string {
	t, err := time.Parse("2006-01-02", dateStr)
	if err != nil {
		t, err = time.Parse("2006-01-02T15:04:05Z", dateStr)
	}
	if err != nil {
		t, err = time.Parse("2006-01-02T15:04:05", dateStr)
	}
	if err != nil {
		return dateStr
	}
	return t.Format("02 Jan 2006")
}

func jobCardDay(dateStr string) string {
	t, err := time.Parse("2006-01-02", dateStr)
	if err != nil {
		t, err = time.Parse("2006-01-02T15:04:05Z", dateStr)
	}
	if err != nil {
		t, err = time.Parse("2006-01-02T15:04:05", dateStr)
	}
	if err != nil {
		return "-"
	}
	return t.Format("Mon")
}

func jobCardClock(t *time.Time) string {
	if t == nil {
		return "-"
	}
	return t.Format("15:04")
}

func jobCardPeriod(start, end string) string {
	s, _ := time.Parse("2006-01-02", start)
	e, _ := time.Parse("2006-01-02", end)
	if s.IsZero() || e.IsZero() {
		return start + " - " + end
	}
	return s.Format("02-01-2006") + " - " + e.Format("02-01-2006")
}

func strOrDash(s *string) string {
	if s == nil || *s == "" {
		return "-"
	}
	return *s
}

// ExportJobCard godoc
//
//	@Summary      Export job card (PDF / Excel)
//	@Description  Export employee job card attendance records to PDF or Excel. When employee_id is empty all filtered employees are exported, grouped by employee.
//	@Tags         Attendance
//	@Security     BearerAuth
//	@Produce      application/octet-stream
//	@Param        format         query string false "Export format: pdf (default) or excel"
//	@Param        lang           query string false "PDF language: en (default) or bn"
//	@Param        start_date     query string false "Start date (YYYY-MM-DD)"
//	@Param        end_date       query string false "End date (YYYY-MM-DD)"
//	@Param        company_id     query string false "Filter by company"
//	@Param        employee_id    query string false "Filter by employee"
//	@Param        department_id  query string false "Filter by department"
//	@Param        section_id     query string false "Filter by section"
//	@Param        designation_id query string false "Filter by designation"
//	@Param        line_id        query string false "Filter by line"
//	@Param        group_id       query string false "Filter by group"
//	@Param        shift_id       query string false "Filter by shift"
//	@Param        status         query string false "Filter by status"
//	@Success      200  {file}  binary
//	@Failure      500  {object}  map[string]string
//	@Router       /attendance/job-card/export [get]
func (h *AttendanceHandler) ExportJobCard(c *gin.Context) {
	startDate := c.DefaultQuery("start_date", time.Now().Format("2006-01-02"))
	endDate := c.DefaultQuery("end_date", time.Now().Format("2006-01-02"))
	format := c.DefaultQuery("format", "pdf")
	lang := c.DefaultQuery("lang", "en")
	companyID := c.Query("company_id")
	employeeID := c.Query("employee_id")
	departmentID := c.Query("department_id")
	sectionID := c.Query("section_id")
	designationID := c.Query("designation_id")
	lineID := c.Query("line_id")
	groupID := c.Query("group_id")
	shiftID := c.Query("shift_id")
	status := c.Query("status")

	if employeeID != "" {
		emp, err := h.employeeRepo.FindByEmployeeID(employeeID)
		if err != nil {
			emp, err = h.employeeRepo.FindByPunchNumber(employeeID)
		}
		if err == nil && emp != nil {
			employeeID = emp.EmployeeID
		}
	}

	endDate = capEndDateToSeparation(h, employeeID, endDate)

	attendances, _, err := h.attendanceRepo.ListJobCard(startDate, endDate, companyID, employeeID, departmentID, sectionID, designationID, lineID, groupID, shiftID, status, 1, 100000)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	sections := groupJobCard(attendances)

	switch format {
	case "excel":
		renderJobCardExcel(c, startDate, endDate, sections)
	default:
		renderJobCardPDF(c, startDate, endDate, lang, sections)
	}
}

func capEndDateToSeparation(h *AttendanceHandler, employeeID, endDate string) string {
	if employeeID == "" {
		return endDate
	}
	sep, err := h.separationRepo.FindProcessedByEmployeeID(employeeID)
	if err == nil && sep != nil && sep.Date != "" {
		sepDate, parseErr := time.Parse("2006-01-02", sep.Date)
		endDateParsed, endParseErr := time.Parse("2006-01-02", endDate)
		if parseErr == nil && endParseErr == nil {
			dayBeforeSep := sepDate.AddDate(0, 0, -1)
			if dayBeforeSep.Before(endDateParsed) {
				return dayBeforeSep.Format("2006-01-02")
			}
		}
	}
	return endDate
}

// --- PDF ---

func renderJobCardPDF(c *gin.Context, startDate, endDate, lang string, sections []jobCardSection) {
	labels := jobCardEnLabels
	if lang == "bn" {
		labels = jobCardBnLabels
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(10, 10, 10)
	pdf.SetAutoPageBreak(false, 0)
	font := loadBanglaFont(pdf)

	company := models.Company{}
	if len(sections) > 0 && len(sections[0].Rows) > 0 {
		company = sections[0].Rows[0].Employee.Company
	}
	period := jobCardPeriod(startDate, endDate)

	for _, sec := range sections {
		pdf.AddPage()
		drawJobCardPage(pdf, font, labels, company, period, sec)
	}

	filename := fmt.Sprintf("job_card_%s_%s.pdf", startDate, endDate)
	if len(sections) == 1 {
		filename = fmt.Sprintf("job_card_%s_%s_%s.pdf", sections[0].Employee.EmployeeID, startDate, endDate)
	}
	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%s", filename))
	if err := pdf.Output(c.Writer); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to generate PDF"})
	}
}

func drawJobCardPage(pdf *gofpdf.Fpdf, font string, labels jobCardLabels, company models.Company, period string, sec jobCardSection) {
	drawJobCardCompanyHeader(pdf, font, labels, company, period)
	drawJobCardInfo(pdf, font, labels, sec)
	drawJobCardTable(pdf, font, labels, sec.Rows)
	drawJobCardSummary(pdf, font, labels, sec.Rows)
	drawJobCardFooter(pdf, font, labels)
}

func drawJobCardCompanyHeader(pdf *gofpdf.Fpdf, font string, labels jobCardLabels, company models.Company, period string) {
	companyName := companyDisplayName(company)
	pdf.SetFillColor(29, 78, 137)
	pdf.Rect(0, 0, 210, 22, "F")
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont(font, "B", 13)
	pdf.SetXY(10, 3.5)
	pdf.CellFormat(190, 6, companyName, "", 0, "C", false, 0, "")
	pdf.SetFont(font, "B", 10)
	pdf.SetXY(10, 10.5)
	pdf.CellFormat(190, 5, labels.JobCardTitle, "", 0, "C", false, 0, "")
	pdf.SetFont(font, "", 8)
	pdf.SetXY(10, 16.5)
	pdf.CellFormat(190, 4, labels.PeriodLabel+": "+period, "", 0, "C", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.SetY(26)
}

func drawJobCardInfo(pdf *gofpdf.Fpdf, font string, labels jobCardLabels, sec jobCardSection) {
	emp := sec.Employee
	y := pdf.GetY()

	pdf.SetFont(font, "B", 8)
	pdf.SetTextColor(29, 78, 137)
	pdf.SetXY(10, y)
	pdf.CellFormat(190, 4, labels.EmployeeInfo, "", 0, "L", false, 0, "")
	pdf.SetDrawColor(29, 78, 137)
	pdf.SetLineWidth(0.3)
	pdf.Line(10, y+4.5, 200, y+4.5)
	y += 7

	name := emp.NameEn
	if name == "" {
		name = emp.NameBn
	}
	desig := ""
	if emp.DesignationRef != nil {
		desig = emp.DesignationRef.Name
		if desig == "" {
			desig = emp.DesignationRef.NameBn
		}
	}
	dept := ""
	if emp.Department != nil {
		dept = emp.Department.Name
		if dept == "" {
			dept = emp.Department.NameBn
		}
	}
	phone := emp.Phone
	joinDate := "-"
	if !emp.JoiningDate.IsZero() {
		joinDate = emp.JoiningDate.Format("02-01-2006")
	}
	shift := ""
	if len(sec.Rows) > 0 && sec.Rows[0].Shift != nil {
		shift = sec.Rows[0].Shift.Name
	}

	pairs := [][2]string{
		{labels.Name, name},
		{labels.EmployeeID, emp.EmployeeID},
		{labels.Designation, desig},
		{labels.Department, dept},
		{labels.Phone, phone},
		{labels.JoiningDate, joinDate},
		{labels.Shift, shift},
		{labels.TotalDays, strconv.Itoa(len(sec.Rows))},
	}

	labelW := 30.0
	valW := 65.0
	rowH := 5.6
	for i, p := range pairs {
		col := i % 2
		rowIdx := i / 2
		x := 10.0
		if col == 1 {
			x = 105.0
		}
		ry := y + float64(rowIdx)*rowH
		pdf.SetFont(font, "B", 8)
		pdf.SetTextColor(90, 90, 90)
		pdf.SetXY(x, ry)
		pdf.CellFormat(labelW, rowH-1, p[0], "", 0, "L", false, 0, "")
		pdf.SetFont(font, "", 8.5)
		pdf.SetTextColor(0, 0, 0)
		pdf.SetXY(x+labelW, ry)
		pdf.CellFormat(valW, rowH-1, p[1], "", 0, "L", false, 0, "")
	}
	pdf.SetY(y + 4*rowH + 3)
}

func drawJobCardTable(pdf *gofpdf.Fpdf, font string, labels jobCardLabels, rows []models.Attendance) {
	x0 := 10.0
	widths := []float64{8, 24, 14, 24, 20, 20, 16, 16, 22, 26}
	headers := []string{labels.Sl, labels.Date, labels.Day, labels.Shift, labels.InTime, labels.OutTime, labels.Hours, labels.OT, labels.LateMinutes, labels.Status}
	rowH := 6.0
	pageH := 297.0
	bottom := 34.0

	y := pdf.GetY()
	drawJobCardTableHeader(pdf, font, x0, y, widths, headers)
	y += rowH

	for i, a := range rows {
		if y+rowH > pageH-bottom {
			pdf.AddPage()
			y = 10
			drawJobCardTableHeader(pdf, font, x0, y, widths, headers)
			y += rowH
		}
		drawJobCardTableRow(pdf, font, x0, y, widths, i+1, a)
		y += rowH
	}
	pdf.SetY(y)
}

func drawJobCardTableHeader(pdf *gofpdf.Fpdf, font string, x0, y float64, widths []float64, headers []string) {
	pdf.SetFillColor(29, 78, 137)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont(font, "B", 7.5)
	cx := x0
	for i, h := range headers {
		pdf.Rect(cx, y, widths[i], 6, "F")
		pdf.SetXY(cx, y+0.5)
		pdf.CellFormat(widths[i], 5, h, "", 0, "C", false, 0, "")
		cx += widths[i]
	}
	pdf.SetTextColor(0, 0, 0)
}

func drawJobCardTableRow(pdf *gofpdf.Fpdf, font string, x0, y float64, widths []float64, idx int, a models.Attendance) {
	shift := ""
	if a.Shift != nil {
		shift = a.Shift.Name
	}
	cells := []string{
		strconv.Itoa(idx),
		jobCardDateDisplay(a.Date),
		jobCardDay(a.Date),
		shift,
		jobCardClock(a.CheckIn),
		jobCardClock(a.CheckOut),
		strOrDash(a.TotalHours),
		strOrDash(a.OverTime),
		strconv.Itoa(a.LateMinutes),
		jobCardStatusCode(a.Status),
	}

	if idx%2 == 0 {
		pdf.SetFillColor(244, 246, 250)
	} else {
		pdf.SetFillColor(255, 255, 255)
	}
	pdf.SetDrawColor(200, 208, 220)
	pdf.SetLineWidth(0.15)

	tc := [3]int{0, 0, 0}
	switch a.Status {
	case "absent":
		tc = [3]int{220, 38, 38}
	case "present":
		tc = [3]int{22, 163, 74}
	case "late":
		tc = [3]int{234, 88, 12}
	case "half_day":
		tc = [3]int{202, 138, 4}
	case "on_leave", "leave":
		tc = [3]int{79, 70, 229}
	case "weekend":
		tc = [3]int{100, 116, 139}
	}

	cx := x0
	pdf.SetFont(font, "", 8)
	for i, cell := range cells {
		pdf.Rect(cx, y, widths[i], 6, "F")
		pdf.Rect(cx, y, widths[i], 6, "D")
		cur := tc
		if i != 9 {
			cur = [3]int{0, 0, 0}
		}
		pdf.SetTextColor(cur[0], cur[1], cur[2])
		pdf.SetXY(cx, y+0.5)
		pdf.CellFormat(widths[i], 5, cell, "", 0, "C", false, 0, "")
		cx += widths[i]
	}
	pdf.SetTextColor(0, 0, 0)
}

func drawJobCardSummary(pdf *gofpdf.Fpdf, font string, labels jobCardLabels, rows []models.Attendance) {
	st := jobCardStatsFor(rows)
	y := pdf.GetY() + 2

	pdf.SetFillColor(238, 242, 248)
	pdf.Rect(10, y, 190, 17, "F")
	pdf.SetFont(font, "B", 8)
	pdf.SetTextColor(29, 78, 137)
	pdf.SetXY(12, y+2)
	pdf.CellFormat(186, 5, labels.Summary, "", 0, "L", false, 0, "")

	pdf.SetFont(font, "", 7.5)
	pdf.SetTextColor(0, 0, 0)
	line1 := fmt.Sprintf("%s: %d    %s: %d    %s: %d    %s: %d    %s: %d",
		labels.TotalDays, st.Total, labels.Present, st.Present, labels.Late, st.Late,
		labels.Absent, st.Absent, labels.HalfDay, st.HalfDay)
	line2 := fmt.Sprintf("%s: %d    %s: %d    %s: %d    %s: %d",
		labels.Leave, st.Leave, labels.Weekend, st.Weekend, labels.Holiday, st.Holiday,
		labels.TotalLateMin, st.LateMinutes)
	pdf.SetXY(12, y+7)
	pdf.CellFormat(186, 4, line1, "", 0, "L", false, 0, "")
	pdf.SetXY(12, y+12)
	pdf.CellFormat(186, 4, line2, "", 0, "L", false, 0, "")
	pdf.SetY(y + 21)
}

func drawJobCardFooter(pdf *gofpdf.Fpdf, font string, labels jobCardLabels) {
	fy := 297.0 - 13
	pdf.SetDrawColor(180, 180, 180)
	pdf.SetLineWidth(0.3)
	pdf.Line(10, fy, 200, fy)
	pdf.SetFont(font, "", 7)
	pdf.SetTextColor(130, 130, 130)
	pdf.SetXY(10, fy+2)
	pdf.CellFormat(95, 4, labels.GeneratedBy, "", 0, "L", false, 0, "")
	pdf.SetXY(105, fy+2)
	pdf.CellFormat(95, 4, labels.PrintDate+": "+time.Now().Format("02-01-2006"), "", 0, "R", false, 0, "")
}

// --- Excel ---

func sanitizeSheetName(name string) string {
	replacer := strings.NewReplacer("[", "", "]", "", ":", "", "*", "", "?", "", "/", "", "\\", "")
	name = replacer.Replace(name)
	name = strings.TrimSpace(name)
	if len(name) > 31 {
		name = name[:31]
	}
	return name
}

func renderJobCardExcel(c *gin.Context, startDate, endDate string, sections []jobCardSection) {
	f := excelize.NewFile()
	defer f.Close()

	company := models.Company{}
	if len(sections) > 0 && len(sections[0].Rows) > 0 {
		company = sections[0].Rows[0].Employee.Company
	}
	companyName := companyDisplayName(company)
	period := jobCardPeriod(startDate, endDate)

	if len(sections) == 0 {
		sections = []jobCardSection{{Employee: models.Employee{}}}
	}

	for i, sec := range sections {
		sheetName := sanitizeSheetName(sec.Employee.EmployeeID)
		if sheetName == "" {
			sheetName = fmt.Sprintf("JobCard%d", i+1)
		}
		if i == 0 {
			f.SetSheetName("Sheet1", sheetName)
		} else {
			f.NewSheet(sheetName)
		}
		fillJobCardSheet(f, sheetName, companyName, period, sec)

		orientation := "portrait"
		paperSize := 9
		fitW := 1
		fitH := 0
		f.SetPageLayout(sheetName, &excelize.PageLayoutOptions{
			Orientation: &orientation, Size: &paperSize, FitToWidth: &fitW, FitToHeight: &fitH,
		})
		f.SetPageMargins(sheetName, &excelize.PageLayoutMarginsOptions{
			Left:   float64Ptr(0.3), Right: float64Ptr(0.3),
			Top:    float64Ptr(0.4), Bottom: float64Ptr(0.4),
			Header: float64Ptr(0), Footer: float64Ptr(0),
		})
		f.SetSheetView(sheetName, -1, &excelize.ViewOptions{ShowGridLines: boolPtr(false)})
	}
	f.SetActiveSheet(0)

	filename := fmt.Sprintf("job_cards_%s_%s.xlsx", startDate, endDate)
	if len(sections) == 1 {
		filename = fmt.Sprintf("job_card_%s_%s_%s.xlsx", sections[0].Employee.EmployeeID, startDate, endDate)
	}
	c.Header("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
	c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%s", filename))
	f.Write(c.Writer)
}

func float64Ptr(f float64) *float64 { return &f }
func boolPtr(b bool) *bool          { return &b }

func fillJobCardSheet(f *excelize.File, sheet, companyName, period string, sec jobCardSection) {
	cols := []struct {
		header string
		width  float64
	}{
		{"#", 5},
		{"Date", 14},
		{"Day", 8},
		{"Shift", 16},
		{"In Time", 12},
		{"Out Time", 12},
		{"Hours", 10},
		{"OT", 10},
		{"Late (min)", 12},
		{"Status", 12},
	}
	nCols := len(cols)

	thinBorder := []excelize.Border{
		{Type: "left", Color: "B0B7C3", Style: 1},
		{Type: "top", Color: "B0B7C3", Style: 1},
		{Type: "bottom", Color: "B0B7C3", Style: 1},
		{Type: "right", Color: "B0B7C3", Style: 1},
	}

	bandStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 15, Family: "Calibri", Color: "FFFFFF"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"1D4E89"}, Pattern: 1},
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})
	bandSubStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 12, Family: "Calibri", Color: "FFFFFF"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"1D4E89"}, Pattern: 1},
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})
	periodStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Size: 11, Family: "Calibri", Color: "000000"},
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})
	sectionLabelStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 11, Family: "Calibri", Color: "1D4E89"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"DDEBF7"}, Pattern: 1},
		Alignment: &excelize.Alignment{Horizontal: "left", Vertical: "center"},
	})
	infoLabelStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 10, Family: "Calibri", Color: "595959"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"F2F2F2"}, Pattern: 1},
		Border:    thinBorder,
		Alignment: &excelize.Alignment{Horizontal: "left", Vertical: "center"},
	})
	infoValueStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Size: 10, Family: "Calibri", Color: "000000"},
		Border:    thinBorder,
		Alignment: &excelize.Alignment{Horizontal: "left", Vertical: "center"},
	})
	headerCellStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 11, Family: "Calibri", Color: "FFFFFF"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"1D4E89"}, Pattern: 1},
		Border:    thinBorder,
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center", WrapText: true},
	})
	dataStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Size: 10, Family: "Calibri", Color: "000000"},
		Border:    thinBorder,
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})
	dataAltStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Size: 10, Family: "Calibri", Color: "000000"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"F2F5FA"}, Pattern: 1},
		Border:    thinBorder,
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})
	redStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 10, Family: "Calibri", Color: "DC2626"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"FEF2F2"}, Pattern: 1},
		Border:    thinBorder,
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})
	greenStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 10, Family: "Calibri", Color: "16A34A"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"F0FDF4"}, Pattern: 1},
		Border:    thinBorder,
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})
	orangeStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 10, Family: "Calibri", Color: "EA580C"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"FFF7ED"}, Pattern: 1},
		Border:    thinBorder,
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})
	purpleStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 10, Family: "Calibri", Color: "4F46E5"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"EEF2FF"}, Pattern: 1},
		Border:    thinBorder,
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})
	grayStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 10, Family: "Calibri", Color: "64748B"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"F1F5F9"}, Pattern: 1},
		Border:    thinBorder,
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})
	summaryStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Size: 10, Family: "Calibri", Color: "1D4E89"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"DDEBF7"}, Pattern: 1},
		Alignment: &excelize.Alignment{Horizontal: "left", Vertical: "center"},
	})
	footerStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Size: 9, Family: "Calibri", Color: "808080"},
		Alignment: &excelize.Alignment{Horizontal: "left", Vertical: "center"},
	})

	for i, col := range cols {
		f.SetColWidth(sheet, colNameAttendance(i+1), colNameAttendance(i+1), col.width)
	}
	endCol := colNameAttendance(nCols)

	// Row 1: company name (band)
	f.SetCellValue(sheet, "A1", companyName)
	f.MergeCell(sheet, "A1", endCol+"1")
	f.SetCellStyle(sheet, "A1", endCol+"1", bandStyle)
	f.SetRowHeight(sheet, 1, 28)

	// Row 2: report title (band)
	f.SetCellValue(sheet, "A2", "JOB CARD")
	f.MergeCell(sheet, "A2", endCol+"2")
	f.SetCellStyle(sheet, "A2", endCol+"2", bandSubStyle)
	f.SetRowHeight(sheet, 2, 22)

	// Row 3: period
	f.SetCellValue(sheet, "A3", "Period: "+period)
	f.MergeCell(sheet, "A3", endCol+"3")
	f.SetCellStyle(sheet, "A3", endCol+"3", periodStyle)
	f.SetRowHeight(sheet, 3, 18)

	// Row 4: blank
	f.SetRowHeight(sheet, 4, 6)

	// Row 5: employee information section label
	f.SetCellValue(sheet, "A5", "EMPLOYEE INFORMATION")
	f.MergeCell(sheet, "A5", endCol+"5")
	f.SetCellStyle(sheet, "A5", endCol+"5", sectionLabelStyle)
	f.SetRowHeight(sheet, 5, 20)

	// Rows 6-9: info grid (label, value, label, value)
	emp := sec.Employee
	name := emp.NameEn
	if name == "" {
		name = emp.NameBn
	}
	desig := ""
	if emp.DesignationRef != nil {
		desig = emp.DesignationRef.Name
		if desig == "" {
			desig = emp.DesignationRef.NameBn
		}
	}
	dept := ""
	if emp.Department != nil {
		dept = emp.Department.Name
		if dept == "" {
			dept = emp.Department.NameBn
		}
	}
	phone := emp.Phone
	joinDate := "-"
	if !emp.JoiningDate.IsZero() {
		joinDate = emp.JoiningDate.Format("02-01-2006")
	}
	shift := ""
	if len(sec.Rows) > 0 && sec.Rows[0].Shift != nil {
		shift = sec.Rows[0].Shift.Name
	}

	infoRows := [][4]string{
		{"Name", name, "Employee ID", emp.EmployeeID},
		{"Designation", desig, "Department", dept},
		{"Phone", phone, "Joining Date", joinDate},
		{"Shift", shift, "Days", strconv.Itoa(len(sec.Rows))},
	}
	for i, r := range infoRows {
		row := 6 + i
		f.SetCellValue(sheet, "A"+strconv.Itoa(row), r[0])
		f.SetCellValue(sheet, "B"+strconv.Itoa(row), r[1])
		f.SetCellValue(sheet, "C"+strconv.Itoa(row), r[2])
		f.SetCellValue(sheet, "D"+strconv.Itoa(row), r[3])
		f.MergeCell(sheet, "B"+strconv.Itoa(row), "B"+strconv.Itoa(row))
		f.MergeCell(sheet, "D"+strconv.Itoa(row), endCol+strconv.Itoa(row))
		f.SetCellStyle(sheet, "A"+strconv.Itoa(row), "A"+strconv.Itoa(row), infoLabelStyle)
		f.SetCellStyle(sheet, "B"+strconv.Itoa(row), "B"+strconv.Itoa(row), infoValueStyle)
		f.SetCellStyle(sheet, "C"+strconv.Itoa(row), "C"+strconv.Itoa(row), infoLabelStyle)
		f.SetCellStyle(sheet, "D"+strconv.Itoa(row), endCol+strconv.Itoa(row), infoValueStyle)
		f.SetRowHeight(sheet, row, 18)
	}

	// Row 10: blank
	f.SetRowHeight(sheet, 10, 6)

	// Row 11: table header
	headerRow := 11
	for i, col := range cols {
		cell := colNameAttendance(i+1) + strconv.Itoa(headerRow)
		f.SetCellValue(sheet, cell, col.header)
		f.SetCellStyle(sheet, cell, cell, headerCellStyle)
	}
	f.SetRowHeight(sheet, headerRow, 22)

	// Data rows
	dataStart := headerRow + 1
	for i, a := range sec.Rows {
		row := dataStart + i
		style := dataStyle
		if i%2 == 1 {
			style = dataAltStyle
		}
		cells := []string{
			strconv.Itoa(i + 1),
			jobCardDateDisplay(a.Date),
			jobCardDay(a.Date),
			shiftOf(a),
			jobCardClock(a.CheckIn),
			jobCardClock(a.CheckOut),
			strOrDash(a.TotalHours),
			strOrDash(a.OverTime),
			strconv.Itoa(a.LateMinutes),
			jobCardStatusCode(a.Status),
		}
		for ci, v := range cells {
			cell := colNameAttendance(ci+1) + strconv.Itoa(row)
			f.SetCellValue(sheet, cell, v)
			f.SetCellStyle(sheet, cell, cell, style)
		}
		statusCell := colNameAttendance(nCols) + strconv.Itoa(row)
		switch a.Status {
		case "absent":
			f.SetCellStyle(sheet, statusCell, statusCell, redStyle)
		case "present":
			f.SetCellStyle(sheet, statusCell, statusCell, greenStyle)
		case "late":
			f.SetCellStyle(sheet, statusCell, statusCell, orangeStyle)
		case "half_day":
			f.SetCellStyle(sheet, statusCell, statusCell, orangeStyle)
		case "on_leave", "leave":
			f.SetCellStyle(sheet, statusCell, statusCell, purpleStyle)
		case "weekend":
			f.SetCellStyle(sheet, statusCell, statusCell, grayStyle)
		}
		f.SetRowHeight(sheet, row, 19)
	}

	// Summary
	st := jobCardStatsFor(sec.Rows)
	summaryRow := dataStart + len(sec.Rows) + 1
	summaryLine1 := fmt.Sprintf("Summary:  Total Days: %d   |   Present: %d   |   Late: %d   |   Absent: %d   |   Half Day: %d",
		st.Total, st.Present, st.Late, st.Absent, st.HalfDay)
	summaryLine2 := fmt.Sprintf("Leave: %d   |   Weekend: %d   |   Holiday: %d   |   Late Minutes: %d",
		st.Leave, st.Weekend, st.Holiday, st.LateMinutes)
	f.SetCellValue(sheet, "A"+strconv.Itoa(summaryRow), summaryLine1)
	f.MergeCell(sheet, "A"+strconv.Itoa(summaryRow), endCol+strconv.Itoa(summaryRow))
	f.SetCellStyle(sheet, "A"+strconv.Itoa(summaryRow), endCol+strconv.Itoa(summaryRow), summaryStyle)
	f.SetRowHeight(sheet, summaryRow, 18)
	f.SetCellValue(sheet, "A"+strconv.Itoa(summaryRow+1), summaryLine2)
	f.MergeCell(sheet, "A"+strconv.Itoa(summaryRow+1), endCol+strconv.Itoa(summaryRow+1))
	f.SetCellStyle(sheet, "A"+strconv.Itoa(summaryRow+1), endCol+strconv.Itoa(summaryRow+1), summaryStyle)
	f.SetRowHeight(sheet, summaryRow+1, 18)

	// Footer
	footerRow := summaryRow + 3
	f.SetCellValue(sheet, "A"+strconv.Itoa(footerRow), "Generated by PeopleHub HR & Payroll System")
	f.MergeCell(sheet, "A"+strconv.Itoa(footerRow), endCol+strconv.Itoa(footerRow))
	f.SetCellStyle(sheet, "A"+strconv.Itoa(footerRow), endCol+strconv.Itoa(footerRow), footerStyle)
	f.SetCellValue(sheet, "A"+strconv.Itoa(footerRow+1), "Print Date: "+time.Now().Format("02-01-2006"))
	f.MergeCell(sheet, "A"+strconv.Itoa(footerRow+1), endCol+strconv.Itoa(footerRow+1))
	f.SetCellStyle(sheet, "A"+strconv.Itoa(footerRow+1), endCol+strconv.Itoa(footerRow+1), footerStyle)

	f.SetPanes(sheet, &excelize.Panes{
		Freeze:      true,
		XSplit:      0,
		YSplit:      dataStart - 1,
		TopLeftCell: "A" + strconv.Itoa(dataStart),
		ActivePane:  "bottomLeft",
	})
}

func shiftOf(a models.Attendance) string {
	if a.Shift != nil {
		return a.Shift.Name
	}
	return ""
}
