package handlers

import (
	_ "embed"
	"fmt"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jung-kurt/gofpdf"
	"github.com/shakil5281/peoplehub-api/internal/models"
	"github.com/shakil5281/peoplehub-api/internal/repository"
)

//go:embed assets/NotoSansBengali-Regular.ttf
var notoSansBengaliRegular []byte

//go:embed assets/NotoSansBengali-Bold.ttf
var notoSansBengaliBold []byte

type payslipLabels struct {
	CompanyName string

	PayslipWord    string
	CopyOffice     string
	CopyEmployee   string
	PayrollMonth   string
	PayrollNo      string
	PrintDateLabel string

	EmployeeInfo   string
	EmployeeID     string
	Name           string
	Department     string
	Section        string
	Designation    string
	Grade          string
	Shift          string
	JoiningDate    string
	EmploymentType string
	AccountNo      string
	NID            string

	Attendance string
	WorkingDays string
	Weekend    string
	Holiday    string
	Present    string
	Absent     string
	Leave      string
	Late       string
	OTHours    string

	Earnings    string
	Description string
	Amount      string
	BasicSalary string
	HouseRent   string
	Medical     string
	Transport   string
	Food        string
	OtherAllowance string
	AttendanceBonus string
	Overtime    string
	TotalEarnings string

	Deductions    string
	Tax           string
	PF            string
	Loan          string
	Advance       string
	AbsentDeduct  string
	OtherDeduct   string
	TotalDeduction string

	Summary       string
	GrossSalary   string
	TotalDeductionLine string
	NetSalary     string

	Payment        string
	PaymentMethod  string
	BankTransfer   string
	Cash           string
	MobileBanking  string
	Cheque         string
	TransactionID  string

	PreparedBy   string
	CheckedBy    string
	ApprovedBy   string
	EmployeeSignature string
	GeneratedBy  string
	Confidential string
	CutHere      string
}

var enLabels = payslipLabels{
	PayslipWord:    "PAYSLIP",
	CopyOffice:     "OFFICE COPY",
	CopyEmployee:   "EMPLOYEE COPY",
	PayrollMonth:   "Payroll Month",
	PayrollNo:      "Payroll No.",
	PrintDateLabel: "Print Date",

	EmployeeInfo:   "EMPLOYEE INFORMATION",
	EmployeeID:     "Employee ID",
	Name:           "Name",
	Department:     "Department",
	Section:        "Section",
	Designation:    "Designation",
	Grade:          "Grade",
	Shift:          "Shift",
	JoiningDate:    "Joining Date",
	EmploymentType: "Employment Type",
	AccountNo:      "Account No.",
	NID:            "NID",

	Attendance:  "ATTENDANCE",
	WorkingDays: "Working Days",
	Weekend:     "Weekend",
	Holiday:     "Holiday",
	Present:     "Present",
	Absent:      "Absent",
	Leave:       "Leave",
	Late:        "Late",
	OTHours:     "OT Hours",

	Earnings:    "EARNINGS",
	Description: "Description",
	Amount:      "Amount",
	BasicSalary: "Basic Salary",
	HouseRent:   "House Rent",
	Medical:     "Medical",
	Transport:   "Transport",
	Food:        "Food",
	OtherAllowance: "Other Allowance",
	AttendanceBonus: "Attendance Bonus",
	Overtime:    "Overtime",
	TotalEarnings: "Total Earnings",

	Deductions:    "DEDUCTIONS",
	Tax:           "Tax",
	PF:            "PF",
	Loan:          "Loan",
	Advance:       "Advance",
	AbsentDeduct:  "Absent Deduction",
	OtherDeduct:   "Other Deduction",
	TotalDeduction: "Total Deduction",

	Summary:       "SUMMARY",
	GrossSalary:   "Gross Salary",
	TotalDeductionLine: "Total Deduction",
	NetSalary:     "NET SALARY",

	Payment:       "PAYMENT INFORMATION",
	PaymentMethod: "Payment Method",
	BankTransfer:  "Bank Transfer",
	Cash:          "Cash",
	MobileBanking: "Mobile Banking",
	Cheque:        "Cheque",
	TransactionID: "Transaction ID",

	PreparedBy:   "Prepared By",
	CheckedBy:    "Checked By",
	ApprovedBy:   "Approved By",
	EmployeeSignature: "Employee Signature",
	GeneratedBy:  "Generated By PeopleHub",
	Confidential: "Confidential Document",
	CutHere:      "CUT HERE",
}

var bnLabels = payslipLabels{
	PayslipWord:    "বেতন স্লিপ",
	CopyOffice:     "দপ্তর কপি",
	CopyEmployee:   "কর্মচারী কপি",
	PayrollMonth:   "বেতন মাস",
	PayrollNo:      "বেতন নং",
	PrintDateLabel: "মুদ্রণের তারিখ",

	EmployeeInfo:   "কর্মচারীর তথ্য",
	EmployeeID:     "কর্মচারী আইডি",
	Name:           "নাম",
	Department:     "বিভাগ",
	Section:        "সেকশন",
	Designation:    "পদবি",
	Grade:          "গ্রেড",
	Shift:          "শিফট",
	JoiningDate:    "যোগদানের তারিখ",
	EmploymentType: "কর্মের ধরন",
	AccountNo:      "অ্যাকাউন্ট নং",
	NID:            "এনআইডি",

	Attendance:  "উপস্থিতি",
	WorkingDays: "কর্মদিবস",
	Weekend:     "সাপ্তাহিক ছুটি",
	Holiday:     "ছুটি",
	Present:     "উপস্থিত",
	Absent:      "অনুপস্থিত",
	Leave:       "ছুটির দিন",
	Late:        "দেরি",
	OTHours:     "ওটি ঘণ্টা",

	Earnings:    "আয়",
	Description: "বিবরণ",
	Amount:      "পরিমাণ",
	BasicSalary: "মূল বেতন",
	HouseRent:   "বাড়ি ভাড়া",
	Medical:     "চিকিৎসা",
	Transport:   "যাতায়াত",
	Food:        "খাবার",
	OtherAllowance: "অন্যান্য ভাতা",
	AttendanceBonus: "উপস্থিতি বোনাস",
	Overtime:    "ওভারটাইম",
	TotalEarnings: "মোট আয়",

	Deductions:    "কর্তন",
	Tax:           "কর",
	PF:            "পিএফ",
	Loan:          "ঋণ",
	Advance:       "অগ্রিম",
	AbsentDeduct:  "অনুপস্থিত কর্তন",
	OtherDeduct:   "অন্যান্য কর্তন",
	TotalDeduction: "মোট কর্তন",

	Summary:       "সারসংক্ষেপ",
	GrossSalary:   "মোট বেতন",
	TotalDeductionLine: "মোট কর্তন",
	NetSalary:     "নিট বেতন",

	Payment:       "পরিশোধের তথ্য",
	PaymentMethod: "পরিশোধের মাধ্যম",
	BankTransfer:  "ব্যাংক ট্রান্সফার",
	Cash:          "নগদ",
	MobileBanking: "মোবাইল ব্যাংকিং",
	Cheque:        "চেক",
	TransactionID: "লেনদেন আইডি",

	PreparedBy:   "প্রস্তুতকারী",
	CheckedBy:    "যাচাইকারী",
	ApprovedBy:   "অনুমোদনকারী",
	EmployeeSignature: "কর্মচারীর স্বাক্ষর",
	GeneratedBy:  "পিপলহাব দ্বারা উৎপন্ন",
	Confidential: "গোপনীয় নথি",
	CutHere:      "কাটুন",
}

var bnMonthNames = []string{
	"", "জানুয়ারি", "ফেব্রুয়ারি", "মার্চ", "এপ্রিল", "মে", "জুন",
	"জুলাই", "আগস্ট", "সেপ্টেম্বর", "অক্টোবর", "নভেম্বর", "ডিসেম্বর",
}

func monthName(month int, lang string) string {
	if lang == "bn" {
		return bnMonthNames[month]
	}
	return time.Date(2000, time.Month(month), 1, 0, 0, 0, 0, time.UTC).Format("January")
}

func buildPayslipLabels(lang string, company models.Company) payslipLabels {
	labels := enLabels
	if lang == "bn" {
		labels = bnLabels
	}
	if company.ID != "" {
		if lang == "bn" && company.CompanyNameBn != "" {
			labels.CompanyName = company.CompanyNameBn
		} else {
			labels.CompanyName = company.CompanyNameEn
		}
	}
	if labels.CompanyName == "" {
		labels.CompanyName = labels.PayslipWord
	}
	return labels
}

func formatBdNumber(v float64) string {
	parts := strings.Split(fmt.Sprintf("%.2f", v), ".")
	intPart := parts[0]
	var result strings.Builder
	count := 0
	for i := len(intPart) - 1; i >= 0; i-- {
		result.WriteByte(intPart[i])
		count++
		if count%3 == 0 && i > 0 {
			result.WriteByte(',')
		}
	}
	runes := []rune(result.String())
	for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {
		runes[i], runes[j] = runes[j], runes[i]
	}
	return string(runes) + "." + parts[1]
}

func fmtMoney(v float64) string {
	r := formatBdNumber(v)
	if strings.HasSuffix(r, ".00") {
		r = r[:len(r)-3]
	}
	return r
}

func loadBanglaFont(pdf *gofpdf.Fpdf) string {
	if pdf == nil {
		return "Arial"
	}
	candidates := []struct {
		path string
		bold string
	}{
		{"C:\\Windows\\Fonts\\SutonnyMJ.ttf", "C:\\Windows\\Fonts\\SutonnyMJ-Bold.ttf"},
	}
	for _, cand := range candidates {
		if _, err := os.Stat(cand.path); err != nil {
			continue
		}
		if _, err := os.Stat(cand.bold); err != nil {
			continue
		}
		pdf.AddUTF8Font("Bangla", "", cand.path)
		if pdf.Error() != nil {
			continue
		}
		pdf.AddUTF8Font("Bangla", "B", cand.bold)
		if pdf.Error() != nil {
			continue
		}
		return "Bangla"
	}
	pdf.AddUTF8FontFromBytes("Bangla", "", notoSansBengaliRegular)
	pdf.AddUTF8FontFromBytes("Bangla", "B", notoSansBengaliBold)
	if pdf.Error() == nil {
		return "Bangla"
	}
	return "Arial"
}

// payslipField is a label/value pair for employee info, attendance, payment.
type payslipField struct {
	Label string
	Value string
}

// payslipRow is a description/amount row for earnings and deduction tables.
type payslipRow struct {
	Label  string
	Amount string
}

// payslipCard carries every value needed to render one payslip card.
type payslipCard struct {
	// header
	CompanyName string
	Address     string
	Phone       string
	Email       string
	BrandName   string
	PayslipWord string
	CopyLabel   string
	PayrollMonth string
	PayrollNo   string
	PrintDate   string

	// employee info
	EmployeeInfo []payslipField

	// attendance
	Attendance []payslipField

	// earnings / deductions
	Earnings        []payslipRow
	EarningsTotal   string
	Deductions      []payslipRow
	DeductionsTotal string

	// summary
	GrossSalary string
	NetSalary   string

	// payment
	Payment []payslipField

	// footer
	PreparedBy   string
	CheckedBy    string
	ApprovedBy   string
	EmployeeSig  string
	GeneratedBy  string
	Confidential string
}

func orDash(v string) string {
	if strings.TrimSpace(v) == "" {
		return "-"
	}
	return v
}

func sectionName(s *models.Section, lang string) string {
	if s == nil {
		return ""
	}
	if lang == "bn" && s.NameBn != "" {
		return s.NameBn
	}
	return s.Name
}

func designationName(d *models.Designation, lang string) string {
	if d == nil {
		return ""
	}
	if lang == "bn" && d.NameBn != "" {
		return d.NameBn
	}
	return d.Name
}

func departmentName(d *models.Department, lang string) string {
	if d == nil {
		return ""
	}
	if lang == "bn" && d.NameBn != "" {
		return d.NameBn
	}
	return d.Name
}

func companyAddress(c models.Company, lang string) string {
	if lang == "bn" && c.AddressBn != "" {
		return c.AddressBn
	}
	return c.AddressEn
}

func paymentMethodName(acctType string, labels payslipLabels) string {
	switch strings.ToLower(acctType) {
	case "bank", "bank_transfer", "bank-transfer":
		return labels.BankTransfer
	case "cash":
		return labels.Cash
	case "mobile", "mobile_banking", "bkash", "nagad", "rocket":
		return labels.MobileBanking
	case "cheque", "check":
		return labels.Cheque
	default:
		if acctType == "" {
			return labels.BankTransfer
		}
		return acctType
	}
}

func shortPayrollNo(id string) string {
	if len(id) > 10 {
		return strings.ToUpper(id[:10])
	}
	return strings.ToUpper(id)
}

func buildPayslipCard(s *models.Salary, month, year int, lang string, labels payslipLabels) *payslipCard {
	emp := &s.Employee

	card := &payslipCard{
		CompanyName:  labels.CompanyName,
		Address:      companyAddress(s.Company, lang),
		Phone:        s.Company.Phone,
		Email:        s.Company.Email,
		BrandName:    "PeopleHub",
		PayslipWord:  labels.PayslipWord,
		CopyLabel:    labels.CopyOffice,
		PayrollMonth: fmt.Sprintf("%s %d", monthName(month, lang), year),
		PayrollNo:    shortPayrollNo(s.ID),
		PrintDate:    time.Now().Format("02 Jan 2006"),

		EmployeeInfo: []payslipField{
			{labels.EmployeeID, orDash(emp.EmployeeID)},
			{labels.Name, orDash(emp.NameEn)},
			{labels.Department, orDash(departmentName(emp.Department, lang))},
			{labels.Section, orDash(sectionName(emp.SectionRef, lang))},
			{labels.Designation, orDash(designationName(emp.DesignationRef, lang))},
			{labels.Grade, orDash(emp.Grade)},
			{labels.Shift, orDash(shiftName(emp.Shift, lang))},
			{labels.JoiningDate, orDash(formatDate(emp.JoiningDate))},
			{labels.EmploymentType, orDash(emp.EmployeeType)},
			{labels.AccountNo, orDash(emp.AccountNumber)},
			{labels.NID, orDash(emp.NID)},
		},

		Attendance: []payslipField{
			{labels.WorkingDays, fmt.Sprint(s.TotalDays)},
			{labels.Weekend, fmt.Sprint(s.WeekendDays)},
			{labels.Holiday, fmt.Sprint(s.HolidayDays)},
			{labels.Present, fmt.Sprint(s.PresentDays)},
			{labels.Absent, fmt.Sprint(s.AbsentDays)},
			{labels.Leave, fmt.Sprint(s.LeaveDays)},
			{labels.Late, fmt.Sprint(s.LateDays)},
			{labels.OTHours, fmtMoney(s.OvertimeHours)},
		},

		Earnings: []payslipRow{
			{labels.BasicSalary, fmtMoney(s.BasicSalary)},
			{labels.HouseRent, fmtMoney(s.HouseRent)},
			{labels.Medical, fmtMoney(s.MedicalAllowance)},
			{labels.Transport, fmtMoney(s.TransportAllowance)},
			{labels.Food, fmtMoney(s.FoodAllowance)},
			{labels.OtherAllowance, fmtMoney(s.OtherAllowance)},
			{labels.AttendanceBonus, fmtMoney(s.AttendanceBonus)},
			{labels.Overtime, fmtMoney(s.OvertimeAmount)},
		},
		EarningsTotal: fmtMoney(s.GrossSalary),

		Deductions: []payslipRow{
			{labels.Tax, fmtMoney(s.Tax)},
			{labels.PF, fmtMoney(s.ProvidentFund)},
			{labels.Loan, fmtMoney(s.LoanDeduction)},
			{labels.Advance, fmtMoney(s.AdvanceDeduction)},
			{labels.AbsentDeduct, fmtMoney(s.AbsentDeduction)},
			{labels.OtherDeduct, fmtMoney(s.OtherDeduction)},
		},
		DeductionsTotal: fmtMoney(s.TotalDeductions),

		GrossSalary: fmtMoney(s.GrossSalary),
		NetSalary:   fmtMoney(s.NetSalary),

		Payment: []payslipField{
			{labels.PaymentMethod, paymentMethodName(emp.AccountType, labels)},
			{labels.TransactionID, orDash(s.ID)},
		},

		PreparedBy:   labels.PreparedBy,
		CheckedBy:    labels.CheckedBy,
		ApprovedBy:   labels.ApprovedBy,
		EmployeeSig:  labels.EmployeeSignature,
		GeneratedBy:  labels.GeneratedBy,
		Confidential: labels.Confidential,
	}

	return card
}

func shiftName(sh *models.Shift, lang string) string {
	if sh == nil {
		return ""
	}
	return sh.Name
}

func formatDate(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format("02 Jan 2006")
}

// PayslipExport godoc
//
// @Summary      Export payslip(s) to Excel
// @Description  Export a single employee payslip or payslips for all employees in the month as Excel. 4 payslips per A4 page.
// @Tags         Salary
// @Security     BearerAuth
// @Produce      application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
// @Param        company_id     query string false "Company ID (required for all employees)"
// @Param        employee_id    query string false "Employee ID (single payslip)"
// @Param        month          query int    true  "Month (1-12)"
// @Param        year           query int    true  "Year"
// @Param        lang           query string false "Language: en|bn (default en)"
// @Param        department_id  query string false "Filter by department"
// @Param        section_id     query string false "Filter by section"
// @Param        designation_id query string false "Filter by designation"
// @Param        line_id        query string false "Filter by line"
// @Param        group_id       query string false "Filter by group"
// @Success      200  {file}  file
// @Failure      400  {object}  map[string]string
// @Failure      500  {object}  map[string]string
// @Router       /salary/payslip/export [get]
func (h *SalaryHandler) PayslipExport(c *gin.Context) {
	month, year, ok := payslipExportParams(c)
	if !ok {
		return
	}

	lang := c.DefaultQuery("lang", "en")
	if lang != "bn" {
		lang = "en"
	}

	if employeeID := c.Query("employee_id"); employeeID != "" {
		salary, err := h.salaryRepo.FindByEmployeeMonth(employeeID, month, year)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "Salary not found for this employee/month"})
			return
		}
		exportSinglePayslipExcel(c, salary, month, year, lang)
		return
	}

	companyID := c.Query("company_id")
	if companyID == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "company_id is required for all-employee export"})
		return
	}

	salaries, err := h.salaryRepo.ListAllByMonthFiltered(repository.SalaryFilter{
		CompanyID:     companyID,
		Month:         month,
		Year:          year,
		DepartmentID:  c.Query("department_id"),
		SectionID:     c.Query("section_id"),
		DesignationID: c.Query("designation_id"),
		LineID:        c.Query("line_id"),
		GroupID:       c.Query("group_id"),
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	if len(salaries) == 0 {
		c.JSON(http.StatusNotFound, gin.H{"error": "No salary records found for this month"})
		return
	}

	exportBulkPayslipExcel(c, salaries, month, year, lang)
}

// PayslipExportPDF godoc
//
// @Summary      Export payslip(s) to PDF
// @Description  Export a single employee payslip or payslips for all employees in the month as PDF. 4 payslips per A4 page.
// @Tags         Salary
// @Security     BearerAuth
// @Produce      application/pdf
// @Param        company_id     query string false "Company ID (required for all employees)"
// @Param        employee_id    query string false "Employee ID (single payslip)"
// @Param        month          query int    true  "Month (1-12)"
// @Param        year           query int    true  "Year"
// @Param        lang           query string false "Language: en|bn (default en)"
// @Param        department_id  query string false "Filter by department"
// @Param        section_id     query string false "Filter by section"
// @Param        designation_id query string false "Filter by designation"
// @Param        line_id        query string false "Filter by line"
// @Param        group_id       query string false "Filter by group"
// @Success      200  {file}  file
// @Failure      400  {object}  map[string]string
// @Failure      500  {object}  map[string]string
// @Router       /salary/payslip/export/pdf [get]
func (h *SalaryHandler) PayslipExportPDF(c *gin.Context) {
	month, year, ok := payslipExportParams(c)
	if !ok {
		return
	}

	lang := c.DefaultQuery("lang", "en")
	if lang != "bn" {
		lang = "en"
	}

	if employeeID := c.Query("employee_id"); employeeID != "" {
		salary, err := h.salaryRepo.FindByEmployeeMonth(employeeID, month, year)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "Salary not found for this employee/month"})
			return
		}
		exportSinglePayslipPDF(c, salary, month, year, lang)
		return
	}

	companyID := c.Query("company_id")
	if companyID == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "company_id is required for all-employee export"})
		return
	}

	salaries, err := h.salaryRepo.ListAllByMonthFiltered(repository.SalaryFilter{
		CompanyID:     companyID,
		Month:         month,
		Year:          year,
		DepartmentID:  c.Query("department_id"),
		SectionID:     c.Query("section_id"),
		DesignationID: c.Query("designation_id"),
		LineID:        c.Query("line_id"),
		GroupID:       c.Query("group_id"),
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	if len(salaries) == 0 {
		c.JSON(http.StatusNotFound, gin.H{"error": "No salary records found for this month"})
		return
	}

	exportBulkPayslipPDF(c, salaries, month, year, lang)
}

func payslipExportParams(c *gin.Context) (month, year int, ok bool) {
	monthStr := c.Query("month")
	yearStr := c.Query("year")
	month, _ = strconv.Atoi(monthStr)
	year, _ = strconv.Atoi(yearStr)
	if month == 0 || year == 0 {
		c.JSON(http.StatusBadRequest, gin.H{"error": "month and year are required"})
		return 0, 0, false
	}
	return month, year, true
}
